version: '3'

services:
  www:
    image: node:16
    volumes:
      - ./src:/opt/app
    working_dir: /opt/app
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - "3000:3000"
      - "9229:9229"
    command: >
      bash -c "yarn install && yarn dev --inspect"